// AUTO-GENERATED by tools/import_action_icons.py — Figma frame Actions (node 1175:3335)

import action_chat_bubble_outline from "./action-chat-bubble-outline.svg?raw";
import action_cancel_clear from "./action-cancel-clear.svg?raw";
import action_autorenew from "./action-autorenew.svg?raw";
import action_archive from "./action-archive.svg?raw";
import action_announcement from "./action-announcement.svg?raw";
import action_add_circle_outline from "./action-add-circle-outline.svg?raw";
import action_add from "./action-add.svg?raw";
import action_time from "./action-time.svg?raw";
import action_delete from "./action-delete.svg?raw";
import action_date_range from "./action-date-range.svg?raw";
import action_create_new_folder from "./action-create-new-folder.svg?raw";
import action_comment from "./action-comment.svg?raw";
import action_content_copy from "./action-content-copy.svg?raw";
import action_cloud from "./action-cloud.svg?raw";
import action_clear from "./action-clear.svg?raw";
import action_check from "./action-check.svg?raw";
import action_help_outline from "./action-help-outline.svg?raw";
import action_filter_list from "./action-filter-list.svg?raw";
import action_file_upload from "./action-file-upload.svg?raw";
import action_file_download from "./action-file-download.svg?raw";
import action_edit from "./action-edit.svg?raw";
import action_drag_indicator from "./action-drag-indicator.svg?raw";
import action_description from "./action-description.svg?raw";
import action_profile_settings from "./action-profile-settings.svg?raw";
import action_open_in_new from "./action-open-in-new.svg?raw";
import action_lock from "./action-lock.svg?raw";
import action_tag from "./action-tag.svg?raw";
import action_list from "./action-list.svg?raw";
import action_link from "./action-link.svg?raw";
import action_info from "./action-info.svg?raw";
import action_view_column from "./action-view-column.svg?raw";
import action_upload_file from "./action-upload-file.svg?raw";
import action_sort from "./action-sort.svg?raw";
import action_settings from "./action-settings.svg?raw";
import action_search from "./action-search.svg?raw";
import action_save from "./action-save.svg?raw";
import action_resolve_alert from "./action-resolve-alert.svg?raw";
import action_remove from "./action-remove.svg?raw";
import action_prompt_add from "./action-prompt-add.svg?raw";
import action_saved_search from "./action-saved-search.svg?raw";
import action_ai_spark from "./action-ai-spark.svg?raw";
import action_filter_line from "./action-filter-line.svg?raw";
import action_filter_solid from "./action-filter-solid.svg?raw";
import action_visibility_off from "./action-visibility-off.svg?raw";
import action_visibility from "./action-visibility.svg?raw";
import action_view_module from "./action-view-module.svg?raw";
import action_prompt_arrow from "./action-prompt-arrow.svg?raw";

export const ACTION_ICON_NAMES = ["action-chat-bubble-outline", "action-cancel-clear", "action-autorenew", "action-archive", "action-announcement", "action-add-circle-outline", "action-add", "action-time", "action-delete", "action-date-range", "action-create-new-folder", "action-comment", "action-content-copy", "action-cloud", "action-clear", "action-check", "action-help-outline", "action-filter-list", "action-file-upload", "action-file-download", "action-edit", "action-drag-indicator", "action-description", "action-profile-settings", "action-open-in-new", "action-lock", "action-tag", "action-list", "action-link", "action-info", "action-view-column", "action-upload-file", "action-sort", "action-settings", "action-search", "action-save", "action-resolve-alert", "action-remove", "action-prompt-add", "action-saved-search", "action-ai-spark", "action-filter-line", "action-filter-solid", "action-visibility-off", "action-visibility", "action-view-module", "action-prompt-arrow"] as const;

export type ActionIconName = (typeof ACTION_ICON_NAMES)[number];

export const ACTION_RAW_BY_NAME: Record<ActionIconName, string> = {
  "action-chat-bubble-outline": action_chat_bubble_outline,
  "action-cancel-clear": action_cancel_clear,
  "action-autorenew": action_autorenew,
  "action-archive": action_archive,
  "action-announcement": action_announcement,
  "action-add-circle-outline": action_add_circle_outline,
  "action-add": action_add,
  "action-time": action_time,
  "action-delete": action_delete,
  "action-date-range": action_date_range,
  "action-create-new-folder": action_create_new_folder,
  "action-comment": action_comment,
  "action-content-copy": action_content_copy,
  "action-cloud": action_cloud,
  "action-clear": action_clear,
  "action-check": action_check,
  "action-help-outline": action_help_outline,
  "action-filter-list": action_filter_list,
  "action-file-upload": action_file_upload,
  "action-file-download": action_file_download,
  "action-edit": action_edit,
  "action-drag-indicator": action_drag_indicator,
  "action-description": action_description,
  "action-profile-settings": action_profile_settings,
  "action-open-in-new": action_open_in_new,
  "action-lock": action_lock,
  "action-tag": action_tag,
  "action-list": action_list,
  "action-link": action_link,
  "action-info": action_info,
  "action-view-column": action_view_column,
  "action-upload-file": action_upload_file,
  "action-sort": action_sort,
  "action-settings": action_settings,
  "action-search": action_search,
  "action-save": action_save,
  "action-resolve-alert": action_resolve_alert,
  "action-remove": action_remove,
  "action-prompt-add": action_prompt_add,
  "action-saved-search": action_saved_search,
  "action-ai-spark": action_ai_spark,
  "action-filter-line": action_filter_line,
  "action-filter-solid": action_filter_solid,
  "action-visibility-off": action_visibility_off,
  "action-visibility": action_visibility,
  "action-view-module": action_view_module,
  "action-prompt-arrow": action_prompt_arrow,
};
