// Generated by tools/generate_fallback_query_ds_icons.py
// Replace with figma_batch_import_icons.py output when MCP assets return 200.

import extra_bookmark from "./extra-bookmark.svg?raw";
import extra_content_paste from "./extra-content-paste.svg?raw";
import extra_data_exploration from "./extra-data-exploration.svg?raw";
import extra_discover from "./extra-discover.svg?raw";
import extra_do_not_disturb_on from "./extra-do-not-disturb-on.svg?raw";
import extra_email from "./extra-email.svg?raw";
import extra_fingerprint from "./extra-fingerprint.svg?raw";
import extra_flaky from "./extra-flaky.svg?raw";
import extra_local_offer from "./extra-local-offer.svg?raw";
import extra_lock from "./extra-lock.svg?raw";
import extra_lock_open from "./extra-lock-open.svg?raw";
import extra_low_priority from "./extra-low-priority.svg?raw";
import extra_menu from "./extra-menu.svg?raw";
import extra_note_add from "./extra-note-add.svg?raw";
import extra_person_add from "./extra-person-add.svg?raw";
import extra_power_off from "./extra-power-off.svg?raw";
import extra_push_pin from "./extra-push-pin.svg?raw";
import extra_security from "./extra-security.svg?raw";
import extra_share from "./extra-share.svg?raw";
import extra_snooze from "./extra-snooze.svg?raw";
import extra_snooze_alt from "./extra-snooze-alt.svg?raw";
import extra_stop_circle from "./extra-stop-circle.svg?raw";
import extra_test from "./extra-test.svg?raw";
import extra_track_changes from "./extra-track-changes.svg?raw";
import extra_verified from "./extra-verified.svg?raw";

export const EXTRA_ICON_NAMES = ["extra-bookmark", "extra-content-paste", "extra-data-exploration", "extra-discover", "extra-do-not-disturb-on", "extra-email", "extra-fingerprint", "extra-flaky", "extra-local-offer", "extra-lock", "extra-lock-open", "extra-low-priority", "extra-menu", "extra-note-add", "extra-person-add", "extra-power-off", "extra-push-pin", "extra-security", "extra-share", "extra-snooze", "extra-snooze-alt", "extra-stop-circle", "extra-test", "extra-track-changes", "extra-verified"] as const;

export type ExtraIconName = (typeof EXTRA_ICON_NAMES)[number];

export const EXTRA_RAW_BY_NAME: Record<ExtraIconName, string> = {
  "extra-bookmark": extra_bookmark,
  "extra-content-paste": extra_content_paste,
  "extra-data-exploration": extra_data_exploration,
  "extra-discover": extra_discover,
  "extra-do-not-disturb-on": extra_do_not_disturb_on,
  "extra-email": extra_email,
  "extra-fingerprint": extra_fingerprint,
  "extra-flaky": extra_flaky,
  "extra-local-offer": extra_local_offer,
  "extra-lock": extra_lock,
  "extra-lock-open": extra_lock_open,
  "extra-low-priority": extra_low_priority,
  "extra-menu": extra_menu,
  "extra-note-add": extra_note_add,
  "extra-person-add": extra_person_add,
  "extra-power-off": extra_power_off,
  "extra-push-pin": extra_push_pin,
  "extra-security": extra_security,
  "extra-share": extra_share,
  "extra-snooze": extra_snooze,
  "extra-snooze-alt": extra_snooze_alt,
  "extra-stop-circle": extra_stop_circle,
  "extra-test": extra_test,
  "extra-track-changes": extra_track_changes,
  "extra-verified": extra_verified,
};
