// Generated by tools/generate_fallback_query_ds_icons.py
// Replace with figma_batch_import_icons.py output when MCP assets return 200.

import nav_advanced_search from "./nav-advanced-search.svg?raw";
import nav_alerts_filled from "./nav-alerts-filled.svg?raw";
import nav_alerts_outline from "./nav-alerts-outline.svg?raw";
import nav_applications_horizontal from "./nav-applications-horizontal.svg?raw";
import nav_applications_stacked from "./nav-applications-stacked.svg?raw";
import nav_automations from "./nav-automations.svg?raw";
import nav_chat from "./nav-chat.svg?raw";
import nav_collapse from "./nav-collapse.svg?raw";
import nav_connections from "./nav-connections.svg?raw";
import nav_dashboards_filled from "./nav-dashboards-filled.svg?raw";
import nav_dashboards_outline from "./nav-dashboards-outline.svg?raw";
import nav_detections from "./nav-detections.svg?raw";
import nav_downloads from "./nav-downloads.svg?raw";
import nav_endpoint from "./nav-endpoint.svg?raw";
import nav_expand from "./nav-expand.svg?raw";
import nav_favorite from "./nav-favorite.svg?raw";
import nav_federated_joins from "./nav-federated-joins.svg?raw";
import nav_integrations from "./nav-integrations.svg?raw";
import nav_intercom from "./nav-intercom.svg?raw";
import nav_investigations_filled from "./nav-investigations-filled.svg?raw";
import nav_investigations_outline from "./nav-investigations-outline.svg?raw";
import nav_logout from "./nav-logout.svg?raw";
import nav_notifications from "./nav-notifications.svg?raw";
import nav_quick_help from "./nav-quick-help.svg?raw";
import nav_reports from "./nav-reports.svg?raw";
import nav_reports_filled from "./nav-reports-filled.svg?raw";
import nav_star from "./nav-star.svg?raw";
import nav_summary_insights from "./nav-summary-insights.svg?raw";
import nav_tenant_settings from "./nav-tenant-settings.svg?raw";
import nav_tools from "./nav-tools.svg?raw";
import nav_tools_filled from "./nav-tools-filled.svg?raw";

export const NAV_ELEMENT_ICON_NAMES = ["nav-advanced-search", "nav-alerts-filled", "nav-alerts-outline", "nav-applications-horizontal", "nav-applications-stacked", "nav-automations", "nav-chat", "nav-collapse", "nav-connections", "nav-dashboards-filled", "nav-dashboards-outline", "nav-detections", "nav-downloads", "nav-endpoint", "nav-expand", "nav-favorite", "nav-federated-joins", "nav-integrations", "nav-intercom", "nav-investigations-filled", "nav-investigations-outline", "nav-logout", "nav-notifications", "nav-quick-help", "nav-reports", "nav-reports-filled", "nav-star", "nav-summary-insights", "nav-tenant-settings", "nav-tools", "nav-tools-filled"] as const;

export type NavElementIconName = (typeof NAV_ELEMENT_ICON_NAMES)[number];

export const NAV_ELEMENT_RAW_BY_NAME: Record<NavElementIconName, string> = {
  "nav-advanced-search": nav_advanced_search,
  "nav-alerts-filled": nav_alerts_filled,
  "nav-alerts-outline": nav_alerts_outline,
  "nav-applications-horizontal": nav_applications_horizontal,
  "nav-applications-stacked": nav_applications_stacked,
  "nav-automations": nav_automations,
  "nav-chat": nav_chat,
  "nav-collapse": nav_collapse,
  "nav-connections": nav_connections,
  "nav-dashboards-filled": nav_dashboards_filled,
  "nav-dashboards-outline": nav_dashboards_outline,
  "nav-detections": nav_detections,
  "nav-downloads": nav_downloads,
  "nav-endpoint": nav_endpoint,
  "nav-expand": nav_expand,
  "nav-favorite": nav_favorite,
  "nav-federated-joins": nav_federated_joins,
  "nav-integrations": nav_integrations,
  "nav-intercom": nav_intercom,
  "nav-investigations-filled": nav_investigations_filled,
  "nav-investigations-outline": nav_investigations_outline,
  "nav-logout": nav_logout,
  "nav-notifications": nav_notifications,
  "nav-quick-help": nav_quick_help,
  "nav-reports": nav_reports,
  "nav-reports-filled": nav_reports_filled,
  "nav-star": nav_star,
  "nav-summary-insights": nav_summary_insights,
  "nav-tenant-settings": nav_tenant_settings,
  "nav-tools": nav_tools,
  "nav-tools-filled": nav_tools_filled,
};
