// Generated by tools/generate_fallback_query_ds_icons.py
// Replace with figma_batch_import_icons.py output when MCP assets return 200.

import navi_arrow_downward from "./navi-arrow-downward.svg?raw";
import navi_arrow_drop_down from "./navi-arrow-drop-down.svg?raw";
import navi_arrow_drop_up from "./navi-arrow-drop-up.svg?raw";
import navi_arrow_upward from "./navi-arrow-upward.svg?raw";
import navi_chevron_left from "./navi-chevron-left.svg?raw";
import navi_chevron_right from "./navi-chevron-right.svg?raw";
import navi_double_chevron from "./navi-double-chevron.svg?raw";
import navi_expand_less from "./navi-expand-less.svg?raw";
import navi_expand_more from "./navi-expand-more.svg?raw";
import navi_more_vert from "./navi-more-vert.svg?raw";
import navi_refresh from "./navi-refresh.svg?raw";
import navi_replay from "./navi-replay.svg?raw";
import navi_subdirectory_arrow_right from "./navi-subdirectory-arrow-right.svg?raw";

export const NAVI_ICON_NAMES = ["navi-arrow-downward", "navi-arrow-drop-down", "navi-arrow-drop-up", "navi-arrow-upward", "navi-chevron-left", "navi-chevron-right", "navi-double-chevron", "navi-expand-less", "navi-expand-more", "navi-more-vert", "navi-refresh", "navi-replay", "navi-subdirectory-arrow-right"] as const;

export type NaviIconName = (typeof NAVI_ICON_NAMES)[number];

export const NAVI_RAW_BY_NAME: Record<NaviIconName, string> = {
  "navi-arrow-downward": navi_arrow_downward,
  "navi-arrow-drop-down": navi_arrow_drop_down,
  "navi-arrow-drop-up": navi_arrow_drop_up,
  "navi-arrow-upward": navi_arrow_upward,
  "navi-chevron-left": navi_chevron_left,
  "navi-chevron-right": navi_chevron_right,
  "navi-double-chevron": navi_double_chevron,
  "navi-expand-less": navi_expand_less,
  "navi-expand-more": navi_expand_more,
  "navi-more-vert": navi_more_vert,
  "navi-refresh": navi_refresh,
  "navi-replay": navi_replay,
  "navi-subdirectory-arrow-right": navi_subdirectory_arrow_right,
};
