#!/usr/bin/env python3
"""Download Actions frame (Figma node 1175:3335) SVGs from Dev Mode MCP asset host → src/assets/icons."""
from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ICONS = ROOT / "src" / "assets" / "icons"

# (registry key, asset hash without .svg) — order matches Figma MCP get_design_context for node 1175:3335
PAIRS: list[tuple[str, str | None]] = [
    ("action-chat-bubble-outline", "047871ae12546ba08da7e0a5a1940dd4c686a014"),
    ("action-cancel-clear", "0fb475767fc8e7759f3ec4147bf9f3d2c8b11197"),
    ("action-autorenew", "febb3c8ef435a460f9710682f5e2e44414f3e3f2"),
    ("action-archive", "9324b837424781a6f3b55e80f82898c56d4cb4e2"),
    ("action-announcement", "25ff464538977ab891ec8e93d781093a4593a766"),
    ("action-add-circle-outline", "13a844f2c1ccee8180c92b44189c40b5c9009865"),
    ("action-add", "e04b837ec8bcd49cd9f40cf69e70b5698f48e74f"),
    ("action-time", "d178c119c79f02c87dca7c4a486c3d17858a3095"),
    ("action-delete", "af2e9165e1da0e3b1fabbac180acb60761775548"),
    ("action-date-range", "c5c1fecdb34f6b3f1ddbc07a774941e335e04a75"),
    ("action-create-new-folder", "8838d30d3aeb8d53874f9d6a82cd030b1eb0cf7d"),
    ("action-comment", "55387c9dd3f545e0d202663df265039890733a2f"),
    ("action-content-copy", "ed1c9031d815fae0bdfed7993975c6222aa97fe1"),
    ("action-cloud", "0bf7cb63ab564d6b98790ac196758dd6e057cb6f"),
    ("action-clear", "03c91b3b9006b54b5d7a5769ed7824affdcb7711"),
    ("action-check", "18740c6e1388c399da635c27550c9ec9980e94d5"),
    ("action-help-outline", "68902f55e078a181ee0e87a9d172444d6ab8dc4d"),
    ("action-filter-list", "c947e01d624012d76bf9f1d59a1aef7708019f4b"),
    ("action-file-upload", "98997b799290d26e300056fa26803e58b18ad870"),
    ("action-file-download", "ca5a4081f7e7c62b72c1f11a1bcde372061904dc"),
    ("action-edit", "70e91bae2532d9eb57b5ca8a6d92f4348401730b"),
    ("action-drag-indicator", "711c9761acc02e8b49df4d59f77fa6c7ece2bc9b"),
    ("action-description", "54fbfd478be81a766e824303baf25c5215cce240"),
    ("action-profile-settings", "9487ccf85154e4814f4a94cf1e4a4a49e627fcea"),
    ("action-open-in-new", "0323aae3fe31ae79905eeccd6a2ef825e1c03759"),
    ("action-lock", "b78310724b015b8a6f51188a8f6b399e828df428"),
    ("action-tag", "41733c74e5c4e1a0623b91195a6b66cde712de2a"),
    ("action-list", "f1fb9da685fdb3b668a0b03a8f799495adc6ea05"),
    ("action-link", "dbf2aa8fe718ec59307f3835bda22188cd88333a"),
    ("action-info", "b9120930143054aa8f4012eab9fa15d69333cad5"),
    ("action-view-column", "9c63e51f470b530866ea7887fc2c102d6393f6ba"),
    ("action-upload-file", "372b1d8fcc1f60af7b939592bc6a8644d0e2dada"),
    ("action-sort", "4aff7f3c0885c1b2e71ec78a6b3c0b7d64651ca5"),
    ("action-settings", "9cc7299bdbb2f6e5a8560ed763e147ae4a7a2c94"),
    ("action-search", "bf8af7b0c023f02721c55064b2ac7f52fcdeb44d"),
    ("action-save", None),  # MCP export omitted <img>; filled floppy from same frame (screenshot)
    ("action-resolve-alert", "53f710125b6407d90b2dbe0cdacd8013f936b137"),
    ("action-remove", "0d119b0a4cebffff1af9cec74ce85a64ae2a73ac"),
    ("action-prompt-add", "51038fd9661f0b814c85d8792ef3aaa550d9464d"),
    ("action-saved-search", "aa658eb3395195c917ce8024b097988233401b7c"),
    ("action-ai-spark", "54ff731799736b9c919fd724d087461dccb60ffd"),
    ("action-filter-line", "b6bcdf76c0ecd5402cf1280b3d589d9a3fd7a28d"),
    ("action-filter-solid", "eebf78308f053037c558ca1bc8cade09c71ba336"),
    ("action-visibility-off", "0abafee57dff2b0e923fe28064f225409685f96c"),
    ("action-visibility", "1daf2292c08119701729bc024bae01cac04b9c34"),
    ("action-view-module", "b2292660e1b837399e4246ad91271ccb43e37ba6"),
    ("action-prompt-arrow", "2f7997e0b64ad7894a5be78cfa85a1b5fd0568ae"),
]

SAVE_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" aria-hidden="true">
  <path fill="currentColor" d="M17 3H5a2 2 0 00-2 2v14l4-4h10a2 2 0 002-2V5a2 2 0 00-2-2zm0 10H7.83L5 15.83V5h12v8z"/>
  <path fill="currentColor" d="M7 7h6v2H7V7zm0 3h4v1H7v-1z" opacity="0.9"/>
</svg>
"""


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode("utf-8")


def normalize_svg(s: str) -> str:
    s = s.replace('fill="var(--fill-0, black)"', 'fill="currentColor"')
    s = s.replace("fill='var(--fill-0, black)'", 'fill="currentColor"')
    s = re.sub(r'stroke="var\(--stroke-0, black\)"', 'stroke="currentColor"', s)
    return s


def var_name(key: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]", "_", key).strip("_")


def emit_ts(pairs: list[tuple[str, str]]) -> None:
    lines = [
        "// AUTO-GENERATED by tools/import_action_icons.py — Figma frame Actions (node 1175:3335)",
        "",
    ]
    for key, rel in pairs:
        lines.append(f'import {var_name(key)} from "./{rel}?raw";')
    lines.append("")
    lines.append(f"export const ACTION_ICON_NAMES = {json.dumps([k for k, _ in pairs])} as const;")
    lines.append("")
    lines.append("export type ActionIconName = (typeof ACTION_ICON_NAMES)[number];")
    lines.append("")
    lines.append("export const ACTION_RAW_BY_NAME: Record<ActionIconName, string> = {")
    for key, _ in pairs:
        lines.append(f'  "{key}": {var_name(key)},')
    lines.append("};")
    lines.append("")
    (ICONS / "action-icons.ts").write_text("\n".join(lines))


def main() -> None:
    ICONS.mkdir(parents=True, exist_ok=True)
    out_pairs: list[tuple[str, str]] = []
    for key, h in PAIRS:
        fname = f"{key}.svg"
        dest = ICONS / fname
        if h is None:
            dest.write_text(SAVE_SVG.strip() + "\n")
        else:
            for host in ("127.0.0.1", "localhost"):
                url = f"http://{host}:3845/assets/{h}.svg"
                try:
                    svg = normalize_svg(fetch(url))
                    dest.write_text(svg + ("\n" if not svg.endswith("\n") else ""))
                    break
                except Exception:
                    continue
            else:
                raise SystemExit(f"Failed to download {key} ({h}) from MCP asset server")
        out_pairs.append((key, fname))
    emit_ts(out_pairs)
    print("Wrote", len(out_pairs), "action icons + action-icons.ts")


if __name__ == "__main__":
    main()
