#!/usr/bin/env python3
"""Download Connectors Large (Figma frame 802:47947) SVGs from Dev Mode MCP asset host → src/assets/icons.

Reads tools/connectors_large_bundle.txt — one line per icon:
  connector-large-slug=hash@inset+hash@inset+...
  - inset empty after @ means full-bleed (0,0,144,144)
  - inset "6.94" means 6.94% on all sides (CSS inset shorthand 1 value)
  - inset "t_r_b_l" uses underscore-separated percentages (top right bottom left), no % signs

Composite output is a single SVG (viewBox 0 0 144 144) stacking <image href="data:image/svg+xml,...">
so masks / rotations from Figma's React export are approximated when only flat layers are listed.
"""

from __future__ import annotations

import json
import re
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ICONS = ROOT / "src" / "assets" / "icons"
BUNDLE = ROOT / "tools" / "connectors_large_bundle.txt"
CANVAS = 144.0
FETCH_TIMEOUT_S = 20
MAX_WORKERS = 12


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=FETCH_TIMEOUT_S) as r:
        return r.read().decode("utf-8")


def fetch_hash(h: str) -> tuple[str, str]:
    last_err: OSError | None = None
    for host in ("127.0.0.1", "localhost"):
        url = f"http://{host}:3845/assets/{h}.svg"
        try:
            return h, fetch(url)
        except OSError as e:
            last_err = e
    raise RuntimeError(f"failed to download {h}.svg: {last_err}") from last_err


def prefetch_svgs(hashes: set[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
        futs = {ex.submit(fetch_hash, h): h for h in hashes}
        for fut in as_completed(futs):
            h, svg = fut.result()
            out[h] = svg
    return out


def data_uri_svg(svg: str) -> str:
    svg = svg.strip()
    enc = urllib.parse.quote(svg, safe="")
    return f"data:image/svg+xml;charset=utf-8,{enc}"


def parse_inset(spec: str) -> tuple[float, float, float, float]:
    """Return (x, y, w, h) in px for a 144 canvas."""
    spec = spec.strip()
    if not spec:
        return 0.0, 0.0, CANVAS, CANVAS
    parts = [p for p in spec.split("_") if p]
    nums = [float(p) for p in parts]
    if len(nums) == 1:
        t = r = b = l = nums[0]
    elif len(nums) == 2:
        t, b = nums[0], nums[0]
        l, r = nums[1], nums[1]
    elif len(nums) == 4:
        t, r, b, l = nums
    else:
        raise ValueError(f"bad inset spec: {spec!r}")
    x = CANVAS * l / 100.0
    y = CANVAS * t / 100.0
    w = CANVAS * (100.0 - l - r) / 100.0
    h = CANVAS * (100.0 - t - b) / 100.0
    return x, y, w, h


def build_composite(layers: list[tuple[str, str]], cache: dict[str, str]) -> str:
    parts: list[str] = []
    for h, inset in layers:
        svg = cache[h]
        x, y, w, h = parse_inset(inset)
        href = data_uri_svg(svg)
        parts.append(
            f'<image href="{href}" xlink:href="{href}" x="{x:.4f}" y="{y:.4f}" width="{w:.4f}" height="{h:.4f}" preserveAspectRatio="xMidYMid meet"/>'
        )
    body = "\n  ".join(parts)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" '
        f'viewBox="0 0 144 144" width="144" height="144" fill="none" aria-hidden="true">\n'
        f"  {body}\n"
        f"</svg>\n"
    )


def var_name(key: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]", "_", key).strip("_")


def parse_bundle(text: str) -> list[tuple[str, list[tuple[str, str]]]]:
    out: list[tuple[str, list[tuple[str, str]]]] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if not line.startswith("connector-large-"):
            continue
        if "=" not in line:
            raise ValueError(f"bad bundle line: {line!r}")
        key, rest = line.split("=", 1)
        key = key.strip()
        layers: list[tuple[str, str]] = []
        for chunk in rest.split("+"):
            chunk = chunk.strip()
            if not chunk:
                continue
            if "@" not in chunk:
                raise ValueError(f"bad layer chunk: {chunk!r}")
            h, inset = chunk.split("@", 1)
            h = h.strip()
            inset = inset.strip()
            layers.append((h, inset))
        if not layers:
            raise ValueError(f"no layers for {key}")
        out.append((key, layers))
    return out


def emit_ts(pairs: list[tuple[str, str]]) -> None:
    lines = [
        "// AUTO-GENERATED by tools/import_connectors_large_icons.py — Figma Connectors Large (802:47947)",
        "",
    ]
    for key, rel in pairs:
        lines.append(f'import {var_name(key)} from "./{rel}?raw";')
    lines.append("")
    lines.append(f"export const CONNECTOR_LARGE_ICON_NAMES = {json.dumps([k for k, _ in pairs])} as const;")
    lines.append("")
    lines.append("export type ConnectorLargeIconName = (typeof CONNECTOR_LARGE_ICON_NAMES)[number];")
    lines.append("")
    lines.append("export const CONNECTOR_LARGE_RAW_BY_NAME: Record<ConnectorLargeIconName, string> = {")
    for key, _ in pairs:
        lines.append(f'  "{key}": {var_name(key)},')
    lines.append("};")
    lines.append("")
    (ICONS / "connector-large-icons.ts").write_text("\n".join(lines))


def main() -> None:
    if not BUNDLE.is_file():
        raise SystemExit(f"missing {BUNDLE}")
    pairs_spec = parse_bundle(BUNDLE.read_text())
    all_hashes: set[str] = set()
    for _, layers in pairs_spec:
        for h, _ in layers:
            all_hashes.add(h)
    print(f"prefetching {len(all_hashes)} unique asset(s)…")
    cache = prefetch_svgs(all_hashes)
    ICONS.mkdir(parents=True, exist_ok=True)
    out_pairs: list[tuple[str, str]] = []
    for key, layers in pairs_spec:
        fname = f"{key}.svg"
        dest = ICONS / fname
        svg = build_composite(layers, cache)
        dest.write_text(svg)
        out_pairs.append((key, fname))
    emit_ts(out_pairs)
    print(f"wrote {len(out_pairs)} connector-large icons + connector-large-icons.ts")


if __name__ == "__main__":
    main()
